[functions.prepare-login]
verify_jwt = false

[functions.zapier-create-client]
verify_jwt = false

[functions.ingest-client-call-summary]
verify_jwt = false

[functions.webhook-update-client]
verify_jwt = false
